1-intro-to-crud/project/companies/urls.py
from django.conf.urls import url

urlpatterns = [

    url(r'^$', 'companies.views.index', name='index'),
    url(r'^new$', 'companies.views.new', name='new'),
    url(r'^create$', 'companies.views.create', name='create'),
    url(r'^(?P<company_id>[0-9]+)$', 'companies.views.info', name='info'),
    url(r'^(?P<company_id>[0-9]+)/edit_view$', 'companies.views.edit_view', name='edit_view'),
    url(r'^(?P<company_id>[0-9]+)/edit$', 'companies.views.edit', name='edit'),
    url(r'^(?P<company_id>[0-9]+)/delete$', 'companies.views.delete', name='delete'),

]

1-intro-to-crud/project/project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^companies/', include('companies.urls', namespace='companies')),
    url(r'^admin/', include(admin.site.urls)),
]

1-intro-to-crud/project/companies/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

class Company(models.Model):
    name = models.CharField(max_length=64, default="")
    phone = PhoneNumberField()
    email = models.EmailField(default="")

1-intro-to-crud/project/companies/views.py
from django.shortcuts import render, redirect
from companies.models import Company

def index(request):
    companies = Company.objects.all().order_by('name')
    return render(request, 'companies/index.html', {"companies": companies})

def new(request):
    return render(request, 'companies/new.html')

def create(request):
    print(request.POST)
    company_name = request.POST.get("name")
    company_phone = request.POST.get("phone")
    company_email = request.POST.get("email")
    company_object = Company(name=company_name, phone=company_phone, email=company_email)
    company_object.save()
    return redirect("companies:index")

def info(request, company_id):
    company = Company.objects.get(pk=company_id)
    return render(request, "companies/info.html", {"company": company})


def edit_view(request, company_id):
    company = Company.objects.get(pk = company_id)
    return render(request, "companies/edit.html", {"company": company})

def edit(request, company_id):
    company = Company.objects.get(pk=company_id)
    company.name = request.POST.get("name")
    company.phone = request.POST.get("phone")
    company.email = request.POST.get("email")
    company.save()
    return redirect("companies:index")

def delete(request, company_id):
    company = Company.objects.get(pk=company_id)
    company.delete()
    return redirect("companies:index")

1-intro-to-crud/project/companies/templates/companies/edit.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    <div class="header">
        <h1 class="heading">Update Entry - {{company.name}}</h1>
        <a class="create_link" href="{% url 'companies:index' %}">Home</a>
    </div>
    <form name="edit_company" action="{% url 'companies:edit' company.id %}" method="POST">
    {% csrf_token %}
        <p>Company:<input name="name" type="text" value="{{company.name}}"></p>
        <p>Phone:<input name="phone" type="text" value="{{company.phone}}"></p>
        <p>Email:<input name="email" type="text" value="{{company.email}}"></p>
        <input value="Update" type="submit">
    </form>
</body>
</html>

1-intro-to-crud/project/companies/templates/companies/index.html
{% load staticfiles %}
<html>
<head>
	<link rel="stylesheet" type="text/css" href= "{% static 'companies/companies.css' %}">
</head>
	<body>
	<div class="header">
		<h1 class="heading">Client List</h1>
		<a class="create_link" href="{% url 'companies:new' %}">Create New</a>
	</div>
    {% if companies %}
        <ul>
        {%for company in companies %}
            <li><a class="create_link" href="{% url 'companies:info' company.id %}">{{ company.name }}</a></li>
        {%endfor%}
        </ul>
    {%endif%}

	</body>
</html>

1-intro-to-crud/project/companies/templates/companies/info.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    <div class="header">
        <h3>{{company.name}}</h3>
        <a class="create_link" href="{% url 'companies:index' %}">Home</a>
    </div>
    {%if company%}
        <p>Name: {{company.name}}</p>
        <p>Phone: {{company.phone}}</p>
        <p>Email: {{company.email}}</p>
        <a class="create_link" href="{% url 'companies:edit_view' company.id %}">Edit</a>
        <a class="create_link" href="{% url 'companies:delete' company.id %}">Delete</a>
    {%endif%}


</body>
</html>

1-intro-to-crud/project/companies/templates/companies/new.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    <div class="header">
        <h1 class="heading">Create New</h1>
        <a class="create_link" href="{% url 'companies:index' %}">Home</a>
    </div>
    <form name="companies" action="{% url 'companies:create' %}" method="POST">
    {% csrf_token %}
        <p>Company:<input name="name" type="text"></p>
        <p>Phone:<input name="phone" type="text"></p>
        <p>Email:<input name="email" type="text"></p>
        <input name="Create" type="submit">
    </form>

</body>
</html>